CREATE TABLE IF NOT EXISTS PONTOS_TAXI (
    ID INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(56) NOT NULL,
    LAT VARCHAR(21) NOT NULL,
    LNG VARCHAR(21) NOT NULL,
    REGISTER_TIME TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS LINHAS_ONIBUS (
    ID INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CODIGO VARCHAR(7) NOT NULL,
    NOME VARCHAR(56) NOT NULL
);

CREATE TABLE IF NOT EXISTS ITINERARIO_UT (
    ID INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_LINHA INT UNSIGNED NOT NULL,
    LAT VARCHAR(21) NOT NULL,
    LNG VARCHAR(21) NOT NULL,
    FOREIGN KEY (ID_LINHA) REFERENCES LINHAS_ONIBUS(ID)
);
